name: Publish package to NPMjs
on:
  push:
    branches:
      - main

jobs:
  publish_package:
    name: Building the current package version
    runs-on: ubuntu-latest
    steps:
      - name: Switch to branch
        uses: actions/checkout@v4
      
      - name: Installing dependencies
        run: npm install

      - name: Build the package
        run: npm run build
  
      - name: Bump and publish package
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
permissions:
  contents: write
  pages: write
  id-token: write